# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=3000)),
                ('person', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
